FROM yiisoftware/yii2-php:8.3-apache

# Install Xdebug
RUN docker-php-ext-enable xdebug

# Create xdebug configuration file
#COPY xdebug.ini /usr/local/etc/php/conf.d/

# Expose the Xdebug port
#EXPOSE 9003
