
-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `characters`
--

CREATE TABLE `characters` (
  `guid` int UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Global Unique Identifier',
  `account` int UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Account Identifier',
  `name` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `race` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `class` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `gender` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `level` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `xp` int UNSIGNED NOT NULL DEFAULT '0',
  `money` int UNSIGNED NOT NULL DEFAULT '0',
  `skin` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `face` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `hairStyle` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `hairColor` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `facialStyle` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `bankSlots` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `restState` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `playerFlags` int UNSIGNED NOT NULL DEFAULT '0',
  `position_x` float NOT NULL DEFAULT '0',
  `position_y` float NOT NULL DEFAULT '0',
  `position_z` float NOT NULL DEFAULT '0',
  `map` smallint UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Map Identifier',
  `instance_id` int UNSIGNED NOT NULL DEFAULT '0',
  `instance_mode_mask` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `orientation` float NOT NULL DEFAULT '0',
  `taximask` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `online` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `cinematic` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `totaltime` int UNSIGNED NOT NULL DEFAULT '0',
  `leveltime` int UNSIGNED NOT NULL DEFAULT '0',
  `logout_time` int UNSIGNED NOT NULL DEFAULT '0',
  `is_logout_resting` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `rest_bonus` float NOT NULL DEFAULT '0',
  `resettalents_cost` int UNSIGNED NOT NULL DEFAULT '0',
  `resettalents_time` int UNSIGNED NOT NULL DEFAULT '0',
  `trans_x` float NOT NULL DEFAULT '0',
  `trans_y` float NOT NULL DEFAULT '0',
  `trans_z` float NOT NULL DEFAULT '0',
  `trans_o` float NOT NULL DEFAULT '0',
  `transguid` int DEFAULT '0',
  `extra_flags` smallint UNSIGNED NOT NULL DEFAULT '0',
  `stable_slots` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `at_login` smallint UNSIGNED NOT NULL DEFAULT '0',
  `zone` smallint UNSIGNED NOT NULL DEFAULT '0',
  `death_expire_time` int UNSIGNED NOT NULL DEFAULT '0',
  `taxi_path` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `arenaPoints` int UNSIGNED NOT NULL DEFAULT '0',
  `totalHonorPoints` int UNSIGNED NOT NULL DEFAULT '0',
  `todayHonorPoints` int UNSIGNED NOT NULL DEFAULT '0',
  `yesterdayHonorPoints` int UNSIGNED NOT NULL DEFAULT '0',
  `totalKills` int UNSIGNED NOT NULL DEFAULT '0',
  `todayKills` smallint UNSIGNED NOT NULL DEFAULT '0',
  `yesterdayKills` smallint UNSIGNED NOT NULL DEFAULT '0',
  `chosenTitle` int UNSIGNED NOT NULL DEFAULT '0',
  `knownCurrencies` bigint UNSIGNED NOT NULL DEFAULT '0',
  `watchedFaction` int UNSIGNED NOT NULL DEFAULT '0',
  `drunk` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `health` int UNSIGNED NOT NULL DEFAULT '0',
  `power1` int UNSIGNED NOT NULL DEFAULT '0',
  `power2` int UNSIGNED NOT NULL DEFAULT '0',
  `power3` int UNSIGNED NOT NULL DEFAULT '0',
  `power4` int UNSIGNED NOT NULL DEFAULT '0',
  `power5` int UNSIGNED NOT NULL DEFAULT '0',
  `power6` int UNSIGNED NOT NULL DEFAULT '0',
  `power7` int UNSIGNED NOT NULL DEFAULT '0',
  `latency` int UNSIGNED DEFAULT '0',
  `talentGroupsCount` tinyint UNSIGNED NOT NULL DEFAULT '1',
  `activeTalentGroup` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `exploredZones` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `equipmentCache` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `ammoId` int UNSIGNED NOT NULL DEFAULT '0',
  `knownTitles` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `actionBars` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `grantableLevels` tinyint UNSIGNED NOT NULL DEFAULT '0',
  `order` tinyint DEFAULT NULL,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleteInfos_Account` int UNSIGNED DEFAULT NULL,
  `deleteInfos_Name` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deleteDate` int UNSIGNED DEFAULT NULL,
  `innTriggerId` int UNSIGNED NOT NULL,
  `extraBonusTalentCount` int NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Player System';

--
-- Truncar tablas antes de insertar `characters`
--

TRUNCATE TABLE `characters`;