<?php

namespace app\models\traits;

trait SpellAttrsEx7Trait
{
    const SPELL_ATTR7_ALLOW_SPELL_REFLECTION = 0x00000001;
    const SPELL_ATTR7_NO_TARGET_DURATION_MOD = 0x00000002;
    const SPELL_ATTR7_DISABLE_AURA_WHILE_DEAD = 0x00000004;
    const SPELL_ATTR7_DEBUG_SPELL = 0x00000008;
    const SPELL_ATTR7_TREAT_AS_RAID_BUFF = 0x00000010;
    const SPELL_ATTR7_CAN_BE_MULTI_CAST = 0x00000020;
    const SPELL_ATTR7_DONT_CAUSE_SPELL_PUSHBACK = 0x00000040;
    const SPELL_ATTR7_PREPARE_FOR_VEHICLE_CONTROL_END = 0x00000080;
    const SPELL_ATTR7_HORDE_SPECIFIC_SPELL = 0x00000100;
    const SPELL_ATTR7_ALLIANCE_SPECIFIC_SPELL = 0x00000200;
    const SPELL_ATTR7_DISPEL_REMOVES_CHARGES = 0x00000400;
    const SPELL_ATTR7_CAN_CAUSE_INTERRUPT = 0x00000800;
    const SPELL_ATTR7_CAN_CAUSE_SILENCE = 0x00001000;
    const SPELL_ATTR7_NO_UI_NOT_INTERRUPTIBLE = 0x00002000;
    const SPELL_ATTR7_RECAST_ON_RESUMMON = 0x00004000;
    const SPELL_ATTR7_RESET_SWING_TIMER_AT_SPELL_START = 0x00008000;
    const SPELL_ATTR7_ONLY_IN_SPELLBOOK_UNTIL_LEARNED = 0x00010000;
    const SPELL_ATTR7_DO_NOT_LOG_PVP_KILL = 0x00020000;
    const SPELL_ATTR7_ATTACK_ON_CHARGE_TO_UNIT = 0x00040000;
    const SPELL_ATTR7_REPORT_SPELL_FAILURE_TO_UNIT_TARGET = 0x00080000;
    const SPELL_ATTR7_NO_CLIENT_FAIL_WHILE_STUNNED_FLEEING_CONFUSED = 0x00100000;
    const SPELL_ATTR7_RETAIN_COOLDOWN_THROUGH_LOAD = 0x00200000;
    const SPELL_ATTR7_IGNORES_COLD_WEATHER_FLYING_REQUIREMENT = 0x00400000;
    const SPELL_ATTR7_NO_ATTACK_DODGE = 0x00800000;
    const SPELL_ATTR7_NO_ATTACK_PARRY = 0x01000000;
    const SPELL_ATTR7_NO_ATTACK_MISS = 0x02000000;
    const SPELL_ATTR7_TREAT_AS_NPC_AOE = 0x04000000;
    const SPELL_ATTR7_BYPASS_NO_RESURRECT_AURA = 0x08000000;
    const SPELL_ATTR7_DO_NOT_COUNT_FOR_PVP_SCOREBOARD = 0x10000000;
    const SPELL_ATTR7_REFLECTION_ONLY_DEFENDS = 0x20000000;
    const SPELL_ATTR7_CAN_PROC_FROM_SUPPRESSED_TARGET_PROCS = 0x40000000;
    const SPELL_ATTR7_ALWAYS_CAST_LOG = 0x80000000;

    /**
     * Get the list of spell attributes with their names.
     *
     * @return array
     */
    public static function getSpellAttributesEx7Options()
    {
        return [
            self::SPELL_ATTR7_ALLOW_SPELL_REFLECTION => 'ALLOW_SPELL_REFLECTION',
            self::SPELL_ATTR7_NO_TARGET_DURATION_MOD => 'NO_TARGET_DURATION_MOD',
            self::SPELL_ATTR7_DISABLE_AURA_WHILE_DEAD => 'DISABLE_AURA_WHILE_DEAD',
            self::SPELL_ATTR7_DEBUG_SPELL => 'DEBUG_SPELL',
            self::SPELL_ATTR7_TREAT_AS_RAID_BUFF => 'TREAT_AS_RAID_BUFF',
            self::SPELL_ATTR7_CAN_BE_MULTI_CAST => 'CAN_BE_MULTI_CAST',
            self::SPELL_ATTR7_DONT_CAUSE_SPELL_PUSHBACK => 'DONT_CAUSE_SPELL_PUSHBACK',
            self::SPELL_ATTR7_PREPARE_FOR_VEHICLE_CONTROL_END => 'PREPARE_FOR_VEHICLE_CONTROL_END',
            self::SPELL_ATTR7_HORDE_SPECIFIC_SPELL => 'HORDE_SPECIFIC_SPELL',
            self::SPELL_ATTR7_ALLIANCE_SPECIFIC_SPELL => 'ALLIANCE_SPECIFIC_SPELL',
            self::SPELL_ATTR7_DISPEL_REMOVES_CHARGES => 'DISPEL_REMOVES_CHARGES',
            self::SPELL_ATTR7_CAN_CAUSE_INTERRUPT => 'CAN_CAUSE_INTERRUPT',
            self::SPELL_ATTR7_CAN_CAUSE_SILENCE => 'CAN_CAUSE_SILENCE',
            self::SPELL_ATTR7_NO_UI_NOT_INTERRUPTIBLE => 'NO_UI_NOT_INTERRUPTIBLE',
            self::SPELL_ATTR7_RECAST_ON_RESUMMON => 'RECAST_ON_RESUMMON',
            self::SPELL_ATTR7_RESET_SWING_TIMER_AT_SPELL_START => 'RESET_SWING_TIMER_AT_SPELL_START',
            self::SPELL_ATTR7_ONLY_IN_SPELLBOOK_UNTIL_LEARNED => 'ONLY_IN_SPELLBOOK_UNTIL_LEARNED',
            self::SPELL_ATTR7_DO_NOT_LOG_PVP_KILL => 'DO_NOT_LOG_PVP_KILL',
            self::SPELL_ATTR7_ATTACK_ON_CHARGE_TO_UNIT => 'ATTACK_ON_CHARGE_TO_UNIT',
            self::SPELL_ATTR7_REPORT_SPELL_FAILURE_TO_UNIT_TARGET => 'REPORT_SPELL_FAILURE_TO_UNIT_TARGET',
            self::SPELL_ATTR7_NO_CLIENT_FAIL_WHILE_STUNNED_FLEEING_CONFUSED => 'NO_CLIENT_FAIL_WHILE_STUNNED_FLEEING_CONFUSED',
            self::SPELL_ATTR7_RETAIN_COOLDOWN_THROUGH_LOAD => 'RETAIN_COOLDOWN_THROUGH_LOAD',
            self::SPELL_ATTR7_IGNORES_COLD_WEATHER_FLYING_REQUIREMENT => 'IGNORES_COLD_WEATHER_FLYING_REQUIREMENT',
            self::SPELL_ATTR7_NO_ATTACK_DODGE => 'NO_ATTACK_DODGE',
            self::SPELL_ATTR7_NO_ATTACK_PARRY => 'NO_ATTACK_PARRY',
            self::SPELL_ATTR7_NO_ATTACK_MISS => 'NO_ATTACK_MISS',
            self::SPELL_ATTR7_TREAT_AS_NPC_AOE => 'TREAT_AS_NPC_AOE',
            self::SPELL_ATTR7_BYPASS_NO_RESURRECT_AURA => 'BYPASS_NO_RESURRECT_AURA',
            self::SPELL_ATTR7_DO_NOT_COUNT_FOR_PVP_SCOREBOARD => 'DO_NOT_COUNT_FOR_PVP_SCOREBOARD',
            self::SPELL_ATTR7_REFLECTION_ONLY_DEFENDS => 'REFLECTION_ONLY_DEFENDS',
            self::SPELL_ATTR7_CAN_PROC_FROM_SUPPRESSED_TARGET_PROCS => 'CAN_PROC_FROM_SUPPRESSED_TARGET_PROCS',
            self::SPELL_ATTR7_ALWAYS_CAST_LOG => 'ALWAYS_CAST_LOG',
            // Add more options as needed
        ];
    }

    /**
     * Get the name for a specific spell attribute.
     *
     * @param int $attribute
     * @return string|null
     */
    public static function getSpellAttributesEx7Name($attribute)
    {
        $spellAttributes = self::getSpellAttributesEx7Options();
        return isset($spellAttributes[$attribute]) ? $spellAttributes[$attribute] : null;
    }
}
