<?php

namespace app\models\traits\spell;

trait SpellEffectImplicitTargetTrait
{
    const SPELL_TARGET_UNIT_NONE = 0;
    const SPELL_TARGET_UNIT_CASTER = 1;
    const SPELL_TARGET_UNIT_NEARBY_ENEMY = 2;
    const SPELL_TARGET_UNIT_NEARBY_PARTY = 3;
    const SPELL_TARGET_UNIT_NEARBY_ALLY = 4;
    const SPELL_TARGET_UNIT_PET = 5;
    const SPELL_TARGET_UNIT_TARGET_ENEMY = 6;
    const SPELL_TARGET_UNIT_SRC_AREA_ENTRY = 7;
    const SPELL_TARGET_UNIT_DEST_AREA_ENTRY = 8;
    const SPELL_TARGET_DEST_HOME = 9;
    const SPELL_TARGET_UNIT_SRC_AREA_UNK_11 = 11;
    const SPELL_TARGET_UNIT_SRC_AREA_ENEMY = 15;
    const SPELL_TARGET_UNIT_DEST_AREA_ENEMY = 16;
    const SPELL_TARGET_DEST_DB = 17;
    const SPELL_TARGET_DEST_CASTER = 18;
    const SPELL_TARGET_UNIT_CASTER_AREA_PARTY = 20;
    const SPELL_TARGET_UNIT_TARGET_ALLY = 21;
    const SPELL_TARGET_SRC_CASTER = 22;
    const SPELL_TARGET_GAMEOBJECT_TARGET = 23;
    const SPELL_TARGET_UNIT_CONE_ENEMY_24 = 24;
    const SPELL_TARGET_UNIT_TARGET_ANY = 25;
    const SPELL_TARGET_GAMEOBJECT_ITEM_TARGET = 26;
    const SPELL_TARGET_UNIT_MASTER = 27;
    const SPELL_TARGET_DEST_DYNOBJ_ENEMY = 28;
    const SPELL_TARGET_DEST_DYNOBJ_ALLY = 29;
    const SPELL_TARGET_UNIT_SRC_AREA_ALLY = 30;
    const SPELL_TARGET_UNIT_DEST_AREA_ALLY = 31;
    const SPELL_TARGET_DEST_CASTER_SUMMON = 32;
    const SPELL_TARGET_UNIT_SRC_AREA_PARTY = 33;
    const SPELL_TARGET_UNIT_DEST_AREA_PARTY = 34;
    const SPELL_TARGET_UNIT_TARGET_PARTY = 35;
    const SPELL_TARGET_DEST_CASTER_UNK_36 = 36;
    const SPELL_TARGET_UNIT_LASTTARGET_AREA_PARTY = 37;
    const SPELL_TARGET_UNIT_NEARBY_ENTRY = 38;
    const SPELL_TARGET_DEST_CASTER_FISHING = 39;
    const SPELL_TARGET_GAMEOBJECT_NEARBY_ENTRY = 40;
    const SPELL_TARGET_DEST_CASTER_FRONT_RIGHT = 41;
    const SPELL_TARGET_DEST_CASTER_BACK_RIGHT = 42;
    const SPELL_TARGET_DEST_CASTER_BACK_LEFT = 43;
    const SPELL_TARGET_DEST_CASTER_FRONT_LEFT = 44;
    const SPELL_TARGET_UNIT_TARGET_CHAINHEAL_ALLY = 45;
    const SPELL_TARGET_DEST_NEARBY_ENTRY = 46;
    const SPELL_TARGET_DEST_CASTER_FRONT = 47;
    const SPELL_TARGET_DEST_CASTER_BACK = 48;
    const SPELL_TARGET_DEST_CASTER_RIGHT = 49;
    const SPELL_TARGET_DEST_CASTER_LEFT = 50;
    const SPELL_TARGET_GAMEOBJECT_SRC_AREA = 51;
    const SPELL_TARGET_GAMEOBJECT_DEST_AREA = 52;
    const SPELL_TARGET_DEST_TARGET_ENEMY = 53;
    const SPELL_TARGET_UNIT_CONE_ENEMY_54 = 54;
    const SPELL_TARGET_DEST_CASTER_FRONT_LEAP = 55;
    const SPELL_TARGET_UNIT_CASTER_AREA_RAID = 56;
    const SPELL_TARGET_UNIT_TARGET_RAID = 57;
    const SPELL_TARGET_UNIT_NEARBY_RAID = 58;
    const SPELL_TARGET_UNIT_CONE_ALLY = 59;
    const SPELL_TARGET_UNIT_CONE_ENTRY = 60;
    const SPELL_TARGET_UNIT_TARGET_AREA_RAID_CLASS = 61;
    const SPELL_TARGET_UNK_62 = 62;
    const SPELL_TARGET_DEST_TARGET_ANY = 63;
    const SPELL_TARGET_DEST_TARGET_FRONT = 64;
    const SPELL_TARGET_DEST_TARGET_BACK = 65;
    const SPELL_TARGET_DEST_TARGET_RIGHT = 66;
    const SPELL_TARGET_DEST_TARGET_LEFT = 67;
    const SPELL_TARGET_DEST_TARGET_FRONT_RIGHT = 68;
    const SPELL_TARGET_DEST_TARGET_BACK_RIGHT = 69;
    const SPELL_TARGET_DEST_TARGET_BACK_LEFT = 70;
    const SPELL_TARGET_DEST_TARGET_FRONT_LEFT = 71;
    const SPELL_TARGET_DEST_CASTER_RANDOM = 72;
    const SPELL_TARGET_DEST_CASTER_RADIUS = 73;
    const SPELL_TARGET_DEST_TARGET_RANDOM = 74;
    const SPELL_TARGET_DEST_TARGET_RADIUS = 75;
    const SPELL_TARGET_DEST_CHANNEL_TARGET = 76;
    const SPELL_TARGET_UNIT_CHANNEL_TARGET = 77;
    const SPELL_TARGET_DEST_DEST_FRONT = 78;
    const SPELL_TARGET_DEST_DEST_BACK = 79;
    const SPELL_TARGET_DEST_DEST_RIGHT = 80;
    const SPELL_TARGET_DEST_DEST_LEFT = 81;
    const SPELL_TARGET_DEST_DEST_FRONT_RIGHT = 82;
    const SPELL_TARGET_DEST_DEST_BACK_RIGHT = 83;
    const SPELL_TARGET_DEST_DEST_BACK_LEFT = 84;
    const SPELL_TARGET_DEST_DEST_FRONT_LEFT = 85;
    const SPELL_TARGET_DEST_DEST_RANDOM = 86;
    const SPELL_TARGET_DEST_DEST = 87;
    const SPELL_TARGET_DEST_DYNOBJ_NONE = 88;
    const SPELL_TARGET_DEST_TRAJ = 89;
    const SPELL_TARGET_UNIT_TARGET_MINIPET = 90;
    const SPELL_TARGET_DEST_DEST_RADIUS = 91;
    const SPELL_TARGET_UNIT_SUMMONER = 92;
    const SPELL_TARGET_CORPSE_SRC_AREA_ENEMY = 93;
    const SPELL_TARGET_UNIT_VEHICLE = 94;
    const SPELL_TARGET_UNIT_TARGET_PASSENGER = 95;
    const SPELL_TARGET_UNIT_PASSENGER_0 = 96;
    const SPELL_TARGET_UNIT_PASSENGER_1 = 97;
    const SPELL_TARGET_UNIT_PASSENGER_2 = 98;
    const SPELL_TARGET_UNIT_PASSENGER_3 = 99;
    const SPELL_TARGET_UNIT_PASSENGER_4 = 100;
    const SPELL_TARGET_UNIT_PASSENGER_5 = 101;
    const SPELL_TARGET_UNIT_PASSENGER_6 = 102;
    const SPELL_TARGET_UNIT_PASSENGER_7 = 103;
    const SPELL_TARGET_UNIT_CONE_ENEMY_104 = 104;
    const SPELL_TARGET_UNIT_UNK_105 = 105;
    const SPELL_TARGET_DEST_CHANNEL_CASTER = 106;
    const SPELL_TARGET_UNK_DEST_AREA_UNK_107 = 107;
    const SPELL_TARGET_GAMEOBJECT_CONE = 108;
    const SPELL_TARGET_UNIT_CONE_ENTRY_110 = 110;

    public static function getSpellEffectImplicitTargetOptions()
    {
        return [
            self::SPELL_TARGET_UNIT_NONE => 'None',
            self::SPELL_TARGET_UNIT_CASTER => 'Caster',
            self::SPELL_TARGET_UNIT_NEARBY_ENEMY => 'Nearby Enemy',
            self::SPELL_TARGET_UNIT_NEARBY_PARTY => 'Nearby Party',
            self::SPELL_TARGET_UNIT_NEARBY_ALLY => 'Nearby Ally',
            self::SPELL_TARGET_UNIT_PET => 'Pet',
            self::SPELL_TARGET_UNIT_TARGET_ENEMY => 'Target Enemy',
            self::SPELL_TARGET_UNIT_SRC_AREA_ENTRY => 'Source Area Entry',
            self::SPELL_TARGET_UNIT_DEST_AREA_ENTRY => 'Destination Area Entry',
            self::SPELL_TARGET_DEST_HOME => 'Destination Home',
            self::SPELL_TARGET_UNIT_SRC_AREA_UNK_11 => 'Source Area Unknown 11',
            self::SPELL_TARGET_UNIT_SRC_AREA_ENEMY => 'Source Area Enemy',
            self::SPELL_TARGET_UNIT_DEST_AREA_ENEMY => 'Destination Area Enemy',
            self::SPELL_TARGET_DEST_DB => 'Destination Database',
            self::SPELL_TARGET_DEST_CASTER => 'Destination Caster',
            self::SPELL_TARGET_UNIT_CASTER_AREA_PARTY => 'Caster Area Party',
            self::SPELL_TARGET_UNIT_TARGET_ALLY => 'Target Ally',
            self::SPELL_TARGET_SRC_CASTER => 'Source Caster',
            self::SPELL_TARGET_GAMEOBJECT_TARGET => 'Game Object Target',
            self::SPELL_TARGET_UNIT_CONE_ENEMY_24 => 'Unit Cone Enemy 24',
            self::SPELL_TARGET_UNIT_TARGET_ANY => 'Unit Target Any',
            self::SPELL_TARGET_GAMEOBJECT_ITEM_TARGET => 'Game Object Item Target',
            self::SPELL_TARGET_UNIT_MASTER => 'Unit Master',
            self::SPELL_TARGET_DEST_DYNOBJ_ENEMY => 'Destination Dynamic Object Enemy',
            self::SPELL_TARGET_DEST_DYNOBJ_ALLY => 'Destination Dynamic Object Ally',
            self::SPELL_TARGET_UNIT_SRC_AREA_ALLY => 'Source Area Ally',
            self::SPELL_TARGET_UNIT_DEST_AREA_ALLY => 'Destination Area Ally',
            self::SPELL_TARGET_DEST_CASTER_SUMMON => 'Destination Caster Summon',
            self::SPELL_TARGET_UNIT_SRC_AREA_PARTY => 'Source Area Party',
            self::SPELL_TARGET_UNIT_DEST_AREA_PARTY => 'Destination Area Party',
            self::SPELL_TARGET_UNIT_TARGET_PARTY => 'Target Party',
            self::SPELL_TARGET_DEST_CASTER_UNK_36 => 'Destination Caster Unknown 36',
            self::SPELL_TARGET_UNIT_LASTTARGET_AREA_PARTY => 'Unit Last Target Area Party',
            self::SPELL_TARGET_UNIT_NEARBY_ENTRY => 'Nearby Entry',
            self::SPELL_TARGET_DEST_CASTER_FISHING => 'Destination Caster Fishing',
            self::SPELL_TARGET_GAMEOBJECT_NEARBY_ENTRY => 'Game Object Nearby Entry',
            self::SPELL_TARGET_DEST_CASTER_FRONT_RIGHT => 'Destination Caster Front Right',
            self::SPELL_TARGET_DEST_CASTER_BACK_RIGHT => 'Destination Caster Back Right',
            self::SPELL_TARGET_DEST_CASTER_BACK_LEFT => 'Destination Caster Back Left',
            self::SPELL_TARGET_DEST_CASTER_FRONT_LEFT => 'Destination Caster Front Left',
            self::SPELL_TARGET_UNIT_TARGET_CHAINHEAL_ALLY => 'Unit Target Chain Heal Ally',
            self::SPELL_TARGET_DEST_NEARBY_ENTRY => 'Destination Nearby Entry',
            self::SPELL_TARGET_DEST_CASTER_FRONT => 'Destination Caster Front',
            self::SPELL_TARGET_DEST_CASTER_BACK => 'Destination Caster Back',
            self::SPELL_TARGET_DEST_CASTER_RIGHT => 'Destination Caster Right',
            self::SPELL_TARGET_DEST_CASTER_LEFT => 'Destination Caster Left',
            self::SPELL_TARGET_GAMEOBJECT_SRC_AREA => 'Game Object Source Area',
            self::SPELL_TARGET_GAMEOBJECT_DEST_AREA => 'Game Object Destination Area',
            self::SPELL_TARGET_DEST_TARGET_ENEMY => 'Destination Target Enemy',
            self::SPELL_TARGET_UNIT_CONE_ENEMY_54 => 'Unit Cone Enemy 54',
            self::SPELL_TARGET_DEST_CASTER_FRONT_LEAP => 'Destination Caster Front Leap',
            self::SPELL_TARGET_UNIT_CASTER_AREA_RAID => 'Caster Area Raid',
            self::SPELL_TARGET_UNIT_TARGET_RAID => 'Unit Target Raid',
            self::SPELL_TARGET_UNIT_NEARBY_RAID => 'Nearby Raid',
            self::SPELL_TARGET_UNIT_CONE_ALLY => 'Unit Cone Ally',
            self::SPELL_TARGET_UNIT_CONE_ENTRY => 'Unit Cone Entry',
            self::SPELL_TARGET_UNIT_TARGET_AREA_RAID_CLASS => 'Unit Target Area Raid Class',
            self::SPELL_TARGET_UNK_62 => 'Unknown 62',
            self::SPELL_TARGET_DEST_TARGET_ANY => 'Destination Target Any',
            self::SPELL_TARGET_DEST_TARGET_FRONT => 'Destination Target Front',
            self::SPELL_TARGET_DEST_TARGET_BACK => 'Destination Target Back',
            self::SPELL_TARGET_DEST_TARGET_RIGHT => 'Destination Target Right',
            self::SPELL_TARGET_DEST_TARGET_LEFT => 'Destination Target Left',
            self::SPELL_TARGET_DEST_TARGET_FRONT_RIGHT => 'Destination Target Front Right',
            self::SPELL_TARGET_DEST_TARGET_BACK_RIGHT => 'Destination Target Back Right',
            self::SPELL_TARGET_DEST_TARGET_BACK_LEFT => 'Destination Target Back Left',
            self::SPELL_TARGET_DEST_TARGET_FRONT_LEFT => 'Destination Target Front Left',
            self::SPELL_TARGET_DEST_CASTER_RANDOM => 'Destination Caster Random',
            self::SPELL_TARGET_DEST_CASTER_RADIUS => 'Destination Caster Radius',
            self::SPELL_TARGET_DEST_TARGET_RANDOM => 'Destination Target Random',
            self::SPELL_TARGET_DEST_TARGET_RADIUS => 'Destination Target Radius',
            self::SPELL_TARGET_DEST_CHANNEL_TARGET => 'Destination Channel Target',
            self::SPELL_TARGET_UNIT_CHANNEL_TARGET => 'Unit Channel Target',
            self::SPELL_TARGET_DEST_DEST_FRONT => 'Destination Destination Front',
            self::SPELL_TARGET_DEST_DEST_BACK => 'Destination Destination Back',
            self::SPELL_TARGET_DEST_DEST_RIGHT => 'Destination Destination Right',
            self::SPELL_TARGET_DEST_DEST_LEFT => 'Destination Destination Left',
            self::SPELL_TARGET_DEST_DEST_FRONT_RIGHT => 'Destination Destination Front Right',
            self::SPELL_TARGET_DEST_DEST_BACK_RIGHT => 'Destination Destination Back Right',
            self::SPELL_TARGET_DEST_DEST_BACK_LEFT => 'Destination Destination Back Left',
            self::SPELL_TARGET_DEST_DEST_FRONT_LEFT => 'Destination Destination Front Left',
            self::SPELL_TARGET_DEST_DEST_RANDOM => 'Destination Destination Random',
            self::SPELL_TARGET_DEST_DEST => 'Destination Destination',
            self::SPELL_TARGET_DEST_DYNOBJ_NONE => 'Destination Dynamic Object None',
            self::SPELL_TARGET_DEST_TRAJ => 'Destination Trajectory',
            self::SPELL_TARGET_UNIT_TARGET_MINIPET => 'Unit Target Minipet',
            self::SPELL_TARGET_DEST_DEST_RADIUS => 'Destination Destination Radius',
            self::SPELL_TARGET_UNIT_SUMMONER => 'Unit Summoner',
            self::SPELL_TARGET_CORPSE_SRC_AREA_ENEMY => 'Corpse Source Area Enemy',
            self::SPELL_TARGET_UNIT_VEHICLE => 'Unit Vehicle',
            self::SPELL_TARGET_UNIT_TARGET_PASSENGER => 'Unit Target Passenger',
            self::SPELL_TARGET_UNIT_PASSENGER_0 => 'Unit Passenger 0',
            self::SPELL_TARGET_UNIT_PASSENGER_1 => 'Unit Passenger 1',
            self::SPELL_TARGET_UNIT_PASSENGER_2 => 'Unit Passenger 2',
            self::SPELL_TARGET_UNIT_PASSENGER_3 => 'Unit Passenger 3',
            self::SPELL_TARGET_UNIT_PASSENGER_4 => 'Unit Passenger 4',
            self::SPELL_TARGET_UNIT_PASSENGER_5 => 'Unit Passenger 5',
            self::SPELL_TARGET_UNIT_PASSENGER_6 => 'Unit Passenger 6',
            self::SPELL_TARGET_UNIT_PASSENGER_7 => 'Unit Passenger 7',
            self::SPELL_TARGET_UNIT_CONE_ENEMY_104 => 'Unit Cone Enemy 104',
            self::SPELL_TARGET_UNIT_UNK_105 => 'Unit Unknown 105',
            self::SPELL_TARGET_DEST_CHANNEL_CASTER => 'Destination Channel Caster',
            self::SPELL_TARGET_UNK_DEST_AREA_UNK_107 => 'Unknown Destination Area Unknown 107',
            self::SPELL_TARGET_GAMEOBJECT_CONE => 'Game Object Cone',
            self::SPELL_TARGET_UNIT_CONE_ENTRY_110 => 'Unit Cone Entry 110',
        ];
    }

    public static function getSpellEffectImplicitTargetName($type)
    {
        $options = self::getSpellEffectImplicitTargetOptions();
        return isset($options[$type]) ? $options[$type] : null;
    }
}
