<?php

namespace app\models\traits\spell;

trait SpellAttrsEx4Trait
{
    const SPELL_ATTR4_NONE = 0x00000000;
    const SPELL_ATTR4_NO_CAST_LOG = 0x00000001;
    const SPELL_ATTR4_CLASS_TRIGGER_ONLY_ON_TARGET = 0x00000002;
    const SPELL_ATTR4_AURA_EXPIRES_OFFLINE = 0x00000004;
    const SPELL_ATTR4_NO_HELPFUL_THREAT = 0x00000008;
    const SPELL_ATTR4_NO_HARMFUL_THREAT = 0x00000010;
    const SPELL_ATTR4_ALLOW_CLIENT_TARGETING = 0x00000020;
    const SPELL_ATTR4_CANNOT_BE_STOLEN = 0x00000040;
    const SPELL_ATTR4_ALLOW_CAST_WHILE_CASTING = 0x00000080;
    const SPELL_ATTR4_IGNORE_DAMAGE_TAKEN_MODIFIERS = 0x00000100;
    const SPELL_ATTR4_COMBAT_FEEDBACK_WHEN_USABLE = 0x00000200;
    const SPELL_ATTR4_WEAPON_SPEED_COST_SCALING = 0x00000400;
    const SPELL_ATTR4_NO_PARTIAL_IMMUNITY = 0x00000800;
    const SPELL_ATTR4_AURA_IS_BUFF = 0x00001000;
    const SPELL_ATTR4_DO_NOT_LOG_CASTER = 0x00002000;
    const SPELL_ATTR4_REACTIVE_DAMAGE_PROC = 0x00004000;
    const SPELL_ATTR4_NOT_IN_SPELLBOOK = 0x00008000;
    const SPELL_ATTR4_NOT_IN_ARENA_OR_RATED_BATTLEGROUND = 0x00010000;
    const SPELL_ATTR4_IGNORE_DEFAULT_ARENA_RESTRICTIONS = 0x00020000;
    const SPELL_ATTR4_BOUNCY_CHAIN_MISSILES = 0x00040000;
    const SPELL_ATTR4_ALLOW_PROC_WHILE_SITTING = 0x00080000;
    const SPELL_ATTR4_AURA_NEVER_BOUNCES = 0x00100000;
    const SPELL_ATTR4_ALLOW_ENTERING_ARENA = 0x00200000;
    const SPELL_ATTR4_PROC_SUPPRESS_SWING_ANIM = 0x00400000;
    const SPELL_ATTR4_SUPPRESS_WEAPON_PROCS = 0x00800000;
    const SPELL_ATTR4_AUTO_RANGED_COMBAT = 0x01000000;
    const SPELL_ATTR4_OWNER_POWER_SCALING = 0x02000000;
    const SPELL_ATTR4_ONLY_FLYING_AREAS = 0x04000000;
    const SPELL_ATTR4_FORCE_DISPLAY_CASTBAR = 0x08000000;
    const SPELL_ATTR4_IGNORE_COMBAT_TIMER = 0x10000000;
    const SPELL_ATTR4_AURA_BOUNCE_FAILS_SPELL = 0x20000000;
    const SPELL_ATTR4_OBSOLETE = 0x40000000;
    const SPELL_ATTR4_USE_FACING_FROM_SPELL = 0x80000000;

    /**
     * Get the list of spell attributes with their names.
     *
     * @return array
     */
    public static function getSpellAttributesEx4Options()
    {
        return [
            self::SPELL_ATTR4_NONE => 'NONE',
            self::SPELL_ATTR4_NO_CAST_LOG => 'NO_CAST_LOG',
            self::SPELL_ATTR4_CLASS_TRIGGER_ONLY_ON_TARGET => 'CLASS_TRIGGER_ONLY_ON_TARGET',
            self::SPELL_ATTR4_AURA_EXPIRES_OFFLINE => 'AURA_EXPIRES_OFFLINE',
            self::SPELL_ATTR4_NO_HELPFUL_THREAT => 'NO_HELPFUL_THREAT',
            self::SPELL_ATTR4_NO_HARMFUL_THREAT => 'NO_HARMFUL_THREAT',
            self::SPELL_ATTR4_ALLOW_CLIENT_TARGETING => 'ALLOW_CLIENT_TARGETING',
            self::SPELL_ATTR4_CANNOT_BE_STOLEN => 'CANNOT_BE_STOLEN',
            self::SPELL_ATTR4_ALLOW_CAST_WHILE_CASTING => 'ALLOW_CAST_WHILE_CASTING',
            self::SPELL_ATTR4_IGNORE_DAMAGE_TAKEN_MODIFIERS => 'IGNORE_DAMAGE_TAKEN_MODIFIERS',
            self::SPELL_ATTR4_COMBAT_FEEDBACK_WHEN_USABLE => 'COMBAT_FEEDBACK_WHEN_USABLE',
            self::SPELL_ATTR4_WEAPON_SPEED_COST_SCALING => 'WEAPON_SPEED_COST_SCALING',
            self::SPELL_ATTR4_NO_PARTIAL_IMMUNITY => 'NO_PARTIAL_IMMUNITY',
            self::SPELL_ATTR4_AURA_IS_BUFF => 'AURA_IS_BUFF',
            self::SPELL_ATTR4_DO_NOT_LOG_CASTER => 'DO_NOT_LOG_CASTER',
            self::SPELL_ATTR4_REACTIVE_DAMAGE_PROC => 'REACTIVE_DAMAGE_PROC',
            self::SPELL_ATTR4_NOT_IN_SPELLBOOK => 'NOT_IN_SPELLBOOK',
            self::SPELL_ATTR4_NOT_IN_ARENA_OR_RATED_BATTLEGROUND => 'NOT_IN_ARENA_OR_RATED_BATTLEGROUND',
            self::SPELL_ATTR4_IGNORE_DEFAULT_ARENA_RESTRICTIONS => 'IGNORE_DEFAULT_ARENA_RESTRICTIONS',
            self::SPELL_ATTR4_BOUNCY_CHAIN_MISSILES => 'BOUNCY_CHAIN_MISSILES',
            self::SPELL_ATTR4_ALLOW_PROC_WHILE_SITTING => 'ALLOW_PROC_WHILE_SITTING',
            self::SPELL_ATTR4_AURA_NEVER_BOUNCES => 'AURA_NEVER_BOUNCES',
            self::SPELL_ATTR4_ALLOW_ENTERING_ARENA => 'ALLOW_ENTERING_ARENA',
            self::SPELL_ATTR4_PROC_SUPPRESS_SWING_ANIM => 'PROC_SUPPRESS_SWING_ANIM',
            self::SPELL_ATTR4_SUPPRESS_WEAPON_PROCS => 'SUPPRESS_WEAPON_PROCS',
            self::SPELL_ATTR4_AUTO_RANGED_COMBAT => 'AUTO_RANGED_COMBAT',
            self::SPELL_ATTR4_OWNER_POWER_SCALING => 'OWNER_POWER_SCALING',
            self::SPELL_ATTR4_ONLY_FLYING_AREAS => 'ONLY_FLYING_AREAS',
            self::SPELL_ATTR4_FORCE_DISPLAY_CASTBAR => 'FORCE_DISPLAY_CASTBAR',
            self::SPELL_ATTR4_IGNORE_COMBAT_TIMER => 'IGNORE_COMBAT_TIMER',
            self::SPELL_ATTR4_AURA_BOUNCE_FAILS_SPELL => 'AURA_BOUNCE_FAILS_SPELL',
            self::SPELL_ATTR4_OBSOLETE => 'OBSOLETE',
            self::SPELL_ATTR4_USE_FACING_FROM_SPELL => 'USE_FACING_FROM_SPELL',
            // Add more options as needed
        ];
    }

    /**
     * Get the name for a specific spell attribute.
     *
     * @param int $attribute
     * @return string|null
     */
    public static function getSpellAttributesEx4Name($attribute)
    {
        $spellAttributes = self::getSpellAttributesEx4Options();
        return isset($spellAttributes[$attribute]) ? $spellAttributes[$attribute] : null;
    }
}
