<?php

namespace app\models\traits\spell;

trait SpellAttrsEx1Trait
{
    const SPELL_ATTR1_NONE = 0x00000000;
    const SPELL_ATTR1_DISMISS_PET_FIRST = 0x00000001;
    const SPELL_ATTR1_USE_ALL_MANA = 0x00000002;
    const SPELL_ATTR1_IS_CHANNELED = 0x00000004;
    const SPELL_ATTR1_NO_REDIRECTION = 0x00000008;
    const SPELL_ATTR1_NO_SKILL_INCREASE = 0x00000010;
    const SPELL_ATTR1_ALLOW_WHILE_STEALTHED = 0x00000020;
    const SPELL_ATTR1_IS_SELF_CHANNELLED = 0x00000040;
    const SPELL_ATTR1_NO_REFLECTION = 0x00000080;
    const SPELL_ATTR1_ONLY_PEACEFUL_TARGETS = 0x00000100;
    const SPELL_ATTR1_INITIATES_COMBAT_ENABLES_AUTO_ATTACK = 0x00000200;
    const SPELL_ATTR1_NO_THREAT = 0x00000400;
    const SPELL_ATTR1_AURA_UNIQUE = 0x00000800;
    const SPELL_ATTR1_FAILURE_BREAKS_STEALTH = 0x00001000;
    const SPELL_ATTR1_TOGGLE_FAR_SIGHT = 0x00002000;
    const SPELL_ATTR1_TRACK_TARGET_IN_CHANNEL = 0x00004000;
    const SPELL_ATTR1_IMMUNITY_PURGES_EFFECT = 0x00008000;
    const SPELL_ATTR1_IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS = 0x00010000;
    const SPELL_ATTR1_NO_AUTOCAST_AI = 0x00020000;
    const SPELL_ATTR1_PREVENTS_ANIM = 0x00040000;
    const SPELL_ATTR1_EXCLUDE_CASTER = 0x00080000;
    const SPELL_ATTR1_FINISHING_MOVE_DAMAGE = 0x00100000;
    const SPELL_ATTR1_THREAT_ONLY_ON_MISS = 0x00200000;
    const SPELL_ATTR1_FINISHING_MOVE_DURATION = 0x00400000;
    const SPELL_ATTR1_IGNORE_OWNERS_DEATH = 0x00800000;
    const SPELL_ATTR1_SPECIAL_SKILLUP = 0x01000000;
    const SPELL_ATTR1_AURA_STAYS_AFTER_COMBAT = 0x02000000;
    const SPELL_ATTR1_REQUIRE_ALL_TARGETS = 0x04000000;
    const SPELL_ATTR1_DISCOUNT_POWER_ON_MISS = 0x08000000;
    const SPELL_ATTR1_NO_AURA_ICON = 0x10000000;
    const SPELL_ATTR1_NAME_IN_CHANNEL_BAR = 0x20000000;
    const SPELL_ATTR1_DISPEL_ALL_STACKS = 0x40000000;
    const SPELL_ATTR1_CAST_WHEN_LEARNED = 0x80000000;

    /**
     * Get the list of spell attributes with their names.
     *
     * @return array
     */
    public static function getSpellAttributesEx1Options()
    {
        return [
            self::SPELL_ATTR1_NONE => 'NONE',
            self::SPELL_ATTR1_DISMISS_PET_FIRST => 'DISMISS_PET_FIRST',
            self::SPELL_ATTR1_USE_ALL_MANA => 'USE_ALL_MANA',
            self::SPELL_ATTR1_IS_CHANNELED => 'IS_CHANNELED',
            self::SPELL_ATTR1_NO_REDIRECTION => 'NO_REDIRECTION',
            self::SPELL_ATTR1_NO_SKILL_INCREASE => 'NO_SKILL_INCREASE',
            self::SPELL_ATTR1_ALLOW_WHILE_STEALTHED => 'ALLOW_WHILE_STEALTHED',
            self::SPELL_ATTR1_IS_SELF_CHANNELLED => 'IS_SELF_CHANNELLED',
            self::SPELL_ATTR1_NO_REFLECTION => 'NO_REFLECTION',
            self::SPELL_ATTR1_ONLY_PEACEFUL_TARGETS => 'ONLY_PEACEFUL_TARGETS',
            self::SPELL_ATTR1_INITIATES_COMBAT_ENABLES_AUTO_ATTACK => 'INITIATES_COMBAT_ENABLES_AUTO_ATTACK',
            self::SPELL_ATTR1_NO_THREAT => 'NO_THREAT',
            self::SPELL_ATTR1_AURA_UNIQUE => 'AURA_UNIQUE',
            self::SPELL_ATTR1_FAILURE_BREAKS_STEALTH => 'FAILURE_BREAKS_STEALTH',
            self::SPELL_ATTR1_TOGGLE_FAR_SIGHT => 'TOGGLE_FAR_SIGHT',
            self::SPELL_ATTR1_TRACK_TARGET_IN_CHANNEL => 'TRACK_TARGET_IN_CHANNEL',
            self::SPELL_ATTR1_IMMUNITY_PURGES_EFFECT => 'IMMUNITY_PURGES_EFFECT',
            self::SPELL_ATTR1_IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS => 'IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS',
            self::SPELL_ATTR1_NO_AUTOCAST_AI => 'NO_AUTOCAST_AI',
            self::SPELL_ATTR1_PREVENTS_ANIM => 'PREVENTS_ANIM',
            self::SPELL_ATTR1_EXCLUDE_CASTER => 'EXCLUDE_CASTER',
            self::SPELL_ATTR1_FINISHING_MOVE_DAMAGE => 'FINISHING_MOVE_DAMAGE',
            self::SPELL_ATTR1_THREAT_ONLY_ON_MISS => 'THREAT_ONLY_ON_MISS',
            self::SPELL_ATTR1_FINISHING_MOVE_DURATION => 'FINISHING_MOVE_DURATION',
            self::SPELL_ATTR1_IGNORE_OWNERS_DEATH => 'IGNORE_OWNERS_DEATH',
            self::SPELL_ATTR1_SPECIAL_SKILLUP => 'SPECIAL_SKILLUP',
            self::SPELL_ATTR1_AURA_STAYS_AFTER_COMBAT => 'AURA_STAYS_AFTER_COMBAT',
            self::SPELL_ATTR1_REQUIRE_ALL_TARGETS => 'REQUIRE_ALL_TARGETS',
            self::SPELL_ATTR1_DISCOUNT_POWER_ON_MISS => 'DISCOUNT_POWER_ON_MISS',
            self::SPELL_ATTR1_NO_AURA_ICON => 'NO_AURA_ICON',
            self::SPELL_ATTR1_NAME_IN_CHANNEL_BAR => 'NAME_IN_CHANNEL_BAR',
            self::SPELL_ATTR1_DISPEL_ALL_STACKS => 'DISPEL_ALL_STACKS',
            self::SPELL_ATTR1_CAST_WHEN_LEARNED => 'CAST_WHEN_LEARNED',
            // Add more options as needed
        ];
    }

    /**
     * Get the name for a specific spell attribute.
     *
     * @param int $attribute
     * @return string|null
     */
    public static function getSpellAttributesEx1Name($attribute)
    {
        $spellAttributes = self::getSpellAttributesEx1Options();
        return isset($spellAttributes[$attribute]) ? $spellAttributes[$attribute] : null;
    }
}
